### PR TITLE
Update config to correct use on eclipse

### PR DESCRIPTION
**Pull request by diegobmd**
Update config to correct use on eclipse, isn't necessary activate annotation processor if you execute the eclipseJdt task

### CODE REVIEW

**Comment by tbroyer** [comment]
Is the current documentation really _incorrect_?

My impression was that you wouldn't use `eclipseJdt` when using Buildship; and it could possibly have unexpected consequences if used with other plugins that also customize it. The configuration done by the plugin for `eclipseJdt` is only about enabling annotation processing, so I preferred telling users to manually enable annotation processing in Eclipse (knowing that the annotation-processing-specific configuration files are generated) than executing a task that Buildship is supposed to somehow "replace" **and** that could have other consequences than just enabling annotation processing (things that could conflict with Buildship in some ways, etc.)

But if you can back your claim that `eclipseJdt` would be _more correct_ by an "official" stance from Gradle/Buildship developers, then I'd happily correct the doc. For now, the current doc seems to me _more correct_ than the proposed change.

**Comment by tbroyer** [comment]
Hmm, OK, found that: https://discuss.gradle.org/t/when-does-buildship-eclipse-customization-run/20781/4

> There are two workarounds for now:
> 
> * run `gradle eclipseJdt` after you import (please never run the full `gradle eclipse` task when using Buildship, the two are incompatible)
> * check in your `org.eclipse.jdt.core.prefs`

So `eclipseJdt` seems _safe_, but any idea why it's said to run it _“after you import”_?

Also, in that case, the doc should probably remind explicitly to **not** use the `eclipse` task with Buildship.

WDYT?

**Comment by diegobmd** [comment]
Hi Thomas thank you for reply, is exactly the problem i caught, not necessary after you import, i think you can do before import too, should probably remind explicitly to not use the eclipse

**Comment by tbroyer** [comment]
Documentation updated in 2733da49a41654f08f1924a956456258889ed12e based on above findings.

**Pull request closed without merging**
