### PR TITLE
Split the IDE section into Eclipse and IntelliJ

### PR DESCRIPTION
**Pull request by chrisalice**
I found the current approach meant I skipped over the first paragraph's mention of IDEA and focussed immediately on the second, totally missing the easy route. I think this rewrite should alleviate that.

### CODE REVIEW

**Comment by tbroyer** [comment]
Thanks for the contribution.

I just don't think that `gradle idea` is "ideal". Ideally, I could just use the native Gradle support in IntelliJ and it'd just work. Do you think you could re-word this without "value judgement"? (I'm not a native English speaker so words don't always flow that easily) I really wanted this to be an either/or depending on everyone's own choices: if you prefer this, then it works that way, if you prefer that, then it's different".
(re-reading my original text, I think it really conveys what I want it to; maybe I should just add an introductory paragraph saying there are 2 ways: let Gradle do it, or let the IDE do it? Maybe use that at subsections rather than Eclipse vs. IntelliJ?)

**Comment by cjp39** [comment]
Made the language more neutral. Better?

**Comment by raniejade** [comment]
Might want to mention this in the doc, it will allow IntelliJ to properly find the generated sources.

```
apply plugin: "idea"

idea {
    module {
        generatedSourceDirs += project.file("build/generated/source/apt")
        def excludes = project.files(".gradle")
        excludes += project.buildDir
        excludes -= "generated"
        excludeDirs = excludes.toSet()
    }
}

```

**Comment by tbroyer** [comment]
@raniejade The plugin already does that for you: https://github.com/tbroyer/gradle-apt-plugin/blob/cdb3e0259b0a5b7b87ab17584128d775878c1fdc/src/main/groovy/net/ltgt/gradle/apt/AptPlugin.groovy#L150-L166 (with [partial tests](https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/test/groovy/net/ltgt/gradle/apt/IdeaIntegrationSpec.groovy#L179-L181))

Is it not working for you? How are you importing your project in IntelliJ? `gradle idea` or using IntelliJ's integrated Gradle support?

**Comment by yogurtearl** [comment]
Works for my in Android Studio 2.1
But is DOESN'T seem to work in IntelliJ 2016.1.1

**Comment by yogurtearl** [comment]
Also, I can get it to work in IntelliJ 15.0.5, but not IntelliJ 2016.1.1.
( works without @raniejade 's config above )

Should probably add a caveat about not working in IntelliJ 2016.x

**Comment by frapontillo** [comment]
@raniejade's solution works, can't this be integrated into the plugin somehow?

**Comment by raniejade** [comment]
@yogurtearl You need to update to 2016.1.2 and untick "create separate module per source set." when importing a gradle project for it to work.

**Comment by tbroyer** [comment]
See https://youtrack.jetbrains.com/issueMobile/IDEA-150042 and https://discuss.gradle.org/t/support-for-intellij-2016/15294

**Comment by igouss** [comment]
Is it possible to specify target directory for the generated sources?

**Comment by tbroyer** [comment]
@igouss See #9

**Comment by tbroyer** [comment]
Reworked the _Usage with IDEs_ section, also adding a note about IntelliJ IDEA 2016.1+ "create separate module per source set" as discussed above: 1d0ac4e

**Pull request closed without merging**
